[package]
name = "doop"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
edition = "2021"

[dependencies]
indexmap = "2.1"
timely-master = {workspace = true}
differential-dataflow-master = { path = "../" }
