[package]
name = "degr_dist"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
edition = "2021"

[dependencies]
timely-master = { workspace = true }
differential-dataflow-master = { path = "../../../" }
dd_server = { path = "../../" }

[lib]
crate-type = ["dylib"]
